### ISSUE TITLE
Expanded example?

### ISSUE THREAD

**Issue by caraclarke** [maxisam/angular2-clipboard#10]
I've been looking through this repos demo folder but can't see how to use this aside from needing to add it to the app.module folder. I'm using angular2/typescript and webpack, is there a more full example somewhere online that shows how to import/reference it in my component and component template?

**Comment by maxisam** [comment]
I used it with webpack on my production project too.  The demo application should work. You don't need import/ref in your component. Import/ref should be in your module not component.

**Comment by caraclarke** [comment]
I imported in my module and am not getting any errors from that like it showed in the demo. What I mean is in my template, how do I use it to copy something. I tried referencing it like I have other directives in the past like `<p ngIIclipboard>hello</p>` but I feel like I'm missing something.

Trying to be specific, how to I use it in my template to tell it what I want to be able to copy.

**Comment by caraclarke** [comment]
Apologies, it seems I didn't look at the example closely enough. I think I found my answer

**Comment by maxisam** [comment]
It is all good. Good luck with your project.
