### ISSUE TITLE
Make compatible with the last released version  of Angular 2 

### ISSUE THREAD

**Issue by xcuben** [maxisam/angular2-clipboard#11]
Hi @maxisam,

would any new release with the new released angular2 version be planified ? 
If yes , when ?

Thanks

**Comment by maxisam** [comment]
It will be very soon.

**Comment by xcuben** [comment]
@maxisam  thanks :)

**Comment by maxisam** [comment]
1.0.0 released. It works with Angular2 Typescript2.
