### ISSUE TITLE
Send to clipboard by code (TypeScript)

### ISSUE THREAD

**Issue by rongchaua** [maxisam/angular2-clipboard#14]
Hi,
the current demos show me how I can bind angular2-clipboard to a button click event to copy text of control to clipboard. 
I would like to send text to clipboard, for example, on changed-event of an input. For example, when user changes the text, I would like to send the calculated result directly to clipboard without requiring any action from user. Is it possible? Can you give me a hint how to do that?

**Comment by maxisam** [comment]
I don't know if it is possible, this is just a wrapper directive for clipboard.js. I think you probably need to ask them. 

Honestly, I don't think users would anticipate this  feature anyway, so I probably won't spend time on this.
