### ISSUE TITLE
Clipboard is not defined

### ISSUE THREAD

**Issue by anchenlee** [maxisam/angular2-clipboard#18]
In  'angular2-clipboard/src/clipboard.directive.ts' file, Your code `import Clipboard = require('clipboard');
` make a mistake, chrome does not support this kind of writing

**Comment by maxisam** [comment]
Please try [demo](https://github.com/maxisam/angular2-clipboard/tree/master/demo) code or [plunker](http://embed.plnkr.co/PD4Ap8/)
