### ISSUE TITLE
Unexpected value 'ClipboardModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by lonelyAddict** [maxisam/angular2-clipboard#20]
Just this morning, i got error 'Unexpected value 'ClipboardModule' imported by the module 'AppModule'' in my app. It worked fine last week. I use ver 1.4.0.
I can't use the latest since currently i'm using angular ver 2.0.0.
What's the stable version for angular 2.0.0?
Could you please be advised about this?
Thanks

**Comment by maxisam** [comment]
Do you use webpack ? Try webpack 2.0 and check the package.json. FYI, 2.0.0 is trying to address AoT issue, if you don't use AoT, you can stay with 1.4.0. Nothing really changed.

**Comment by lonelyAddict** [comment]
Okay thanks man.
