### ISSUE TITLE
Unexpected value 't' imported by the module 'ContentManageModule'

### ISSUE THREAD

**Issue by rogueRabbit** [maxisam/angular2-clipboard#21]
when I install the plug-in, but I have made a mistake, Have you ever had this problem? @maxisam

**Comment by maxisam** [comment]
I need more information. Try 1.4.0 version if you don't need AoT.

**Comment by vadym-kukhtin** [comment]
@maxisam Have the same problem - it is some generic problem:
1. Can come from ng2 versions mismatch
2. Or webpack bug
3. Or module bug

I have huge app on ng2 and I am not sure what is causing this error, but I see the problem only in specs. And if I remove ClipboardModule from TestBed config 'imports' - everything is working again.

**Comment by maxisam** [comment]
it is actually webpack issue. Please read my previous comment, or just use 1.4.0 version.

**Comment by maxisam** [comment]
I assumed my suggestion works. This issue is closed.
