### ISSUE TITLE
Error postinstall

### ISSUE THREAD

**Issue by monoflash** [maxisam/angular2-clipboard#3]
npm install angular2-clipboard --save

> angular2-clipboard@0.2.10 postinstall /assets/node_modules/angular2-clipboard
> npm run typings

> angular2-clipboard@0.2.10 typings /assets/node_modules/angular2-clipboard
> typings install --ambient

**typings ERR! deprecated** The "ambient" flag is deprecated. Please use "global" instead

```
$ typings --version
1.0.4
```

**Comment by maxisam** [comment]
it is fixed. please get 0.2.11 thx !
