### ISSUE TITLE
more instructions in README, please?

### ISSUE THREAD

**Issue by jamesmanning** [maxisam/angular2-clipboard#4]
I'm using the module and directive now and it's working great, but I've been fumbling around and if you could, I think it'd be great to give more step-by-step instructions on using it.

The plunker is great, but it's using the angular2-clipboard and clipboard off of npmcdn and it's not clear (at least to someone who hasn't installed third-party directives before) what the "right" system-config.ts changes are, so for now I'm actually using the same npmcdn approach like the plunker is.

I'd love if the README could include a more specific list like:

1. npm install angular2-clipboard --save
1. make these changes to the map and packages in system-config.ts (or however you have SystemJS configured)
1. in the component where you want to use it, import {ClipboardDirective} from 'angular2-clipboard';
1. add ClipboardDirective to the directives array for the component that will use it
1. use in the template per plunker example

NOTE: if I knew the correct instructions, I'd happily do this as a pull request myself, but can't figure out the right systemjs config to get it working from my node_modules version instead of npmcdn

Thanks!!

**Comment by maxisam** [comment]
It is a great idea, but I actually don't use systemJS. So I don't really know the best way to configure it in systemJS for a real project. I am welcome to let others to make a pull request for this.

**Comment by jamesmanning** [comment]
In my particular case, I'm using the angular-cli so I found I needed to add it to the vendor files array first.  Maybe one day that cli will support installing third-party modules from npm and automating the steps listed to do so.

https://github.com/angular/angular-cli/wiki/3rd-party-libs

**Comment by jamesmanning** [comment]
I hope they include some examples that have a dependency tree under them - after adding it as a npm  modules, I had to configure the paths for each of the dependencies for SystemJS to load them, like:

      'angular2-clipboard': 'vendor/angular2-clipboard',
      'clipboard':          'vendor/angular2-clipboard/node_modules/clipboard/lib/clipboard.js',
      'tiny-emitter':       'vendor/angular2-clipboard/node_modules/clipboard/node_modules/tiny-emitter/index.js',
      'good-listener':      'vendor/angular2-clipboard/node_modules/clipboard/node_modules/good-listener/dist/good-listener.js',
      'select':             'vendor/angular2-clipboard/node_modules/clipboard/node_modules/select/dist/select.js',

**Comment by jamesmanning** [comment]
FWIW, I've requested potentially having angular-cli support this kind of scenario (ng install-lib angular2-clipboard).  While not everyone will be using SystemJS, since it's the "default" and what you get using their own CLI, hopefully they can make it easier for new angular2 developers to leverage angular2-clipboard. :smile:

**Comment by maxisam** [comment]
I just added a webpack example under demo folder. It is basically like using angular-cli. I hope this will help.
