### ISSUE TITLE
Error in ngii-clipboard.directive.ts

### ISSUE THREAD

**Issue by xcuben** [maxisam/angular2-clipboard#5]
Hi there,
by installing the Module and trying to run it with my angular2 application.
I've got the following Error Log: 

> ERROR in ./~/angular2-clipboard/src/ngii-clipboard.directive.ts
> (2,28): error TS2307: Cannot find module 'clipboard'.

Is there any Explanation for that ?

Thanks

**Comment by maxisam** [comment]
This module depends on clipboard.js. Please use npm (>3.9) to install it.

**Comment by xcuben** [comment]
I've installed the standard clipboard module in my Package.json --->"clipboard": "^1.5.12"
my npm version is 3.10.5
How do I can call the clipboard.js file in this case ? Is there any other Issues for it ?

**Comment by maxisam** [comment]
First of all, you don't need to installed clipboard module. When you install this module, npm will automatically install clipboard. 

I think you need to check the module system you use in your code. This is more like a general library issue. Do you use any other Angular2 module in your project ?

**Comment by xcuben** [comment]
Indeed yeah 

Here is my package.json:

{
  "name": "app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "clean": "rimraf node_modules doc dist typings && npm cache clean",
    "clean-install": "npm run clean && npm install",
    "clean-start": "npm run clean-install && npm start",
    "watch": "webpack --watch --progress --profile",
    "build": "rimraf dist && webpack --progress --profile --bail",
    "server": "webpack-dev-server --inline --progress --port 8080",
    "webdriver-update": "webdriver-manager update",
    "webdriver-start": "webdriver-manager start",
    "lint": "tslint 'src/**/*.ts'; exit 0",
    "e2e": "protractor",
    "e2e-live": "protractor --elementExplorer",
    "pretest": "npm run lint",
    "test": "karma start",
    "test-watch": "karma start --no-single-run --auto-watch",
    "ci": "npm run e2e && npm run test",
    "docs": "typedoc --options typedoc.json src/app/app.component.ts",
    "start": "npm run server",
    "start-prod": "npm run build && light-server -s dist -p 8080",
    "postinstall": "npm run webdriver-update && typings install"
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "angular2-clipboard": "^0.2.12",
    "angular2-ui-switch": "^1.0.5",
    "bootstrap": "^3.3.6",
    "bootswatch": "^3.3.6",
    "clipboard": "^1.5.12",
    "es6-shim": "^0.35.0",
    "localStorage": "^1.0.3",
    "ng2-bootstrap": "^1.0.16",
    "ngclipboard": "^1.1.1",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "autoprefixer": "^6.3.2",
    "codelyzer": "0.0.19",
    "copy-webpack-plugin": "^3.0.0",
    "css-loader": "^0.23.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.4",
    "font-awesome": "^4.6.3",
    "html-loader": "^0.4.0",
    "html-webpack-plugin": "^2.8.1",
    "istanbul-instrumenter-loader": "^0.2.0",
    "jasmine-core": "^2.3.4",
    "jasmine-spec-reporter": "^2.4.0",
    "json-loader": "^0.5.3",
    "karma": "0.13.22",
    "karma-chrome-launcher": "^1.0.1",
    "karma-coverage": "^1.0.0",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.3",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "1.7.0",
    "light-server": "^1.1.6",
    "node-sass": "^3.4.2",
    "null-loader": "0.1.1",
    "phantomjs-prebuilt": "^2.1.4",
    "postcss-loader": "^0.9.1",
    "protractor": "^3.1.1",
    "raw-loader": "0.5.1",
    "rimraf": "^2.5.1",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "ts-helpers": "^1.1.1",
    "ts-loader": "^0.8.1",
    "tslint": "^3.10.2",
    "tslint-loader": "^2.1.0",
    "typedoc": "^0.3.12",
    "typescript": "^1.8.0",
    "typings": "^0.8.1",
    "url-loader": "^0.5.6",
    "webpack": "^1.12.13",
    "webpack-dev-server": "^1.14.1"
  }
}

**Comment by maxisam** [comment]
It seems right to me. could you remove  "ngclipboard": "^1.1.1" and "clipboard": "^1.5.12" ?

**Comment by xcuben** [comment]
I did it but in vain ...
always getting : 

> ERROR in ./~/angular2-clipboard/src/ngii-clipboard.directive.ts
> (2,28): error TS2307: Cannot find module 'clipboard'.

**Comment by maxisam** [comment]
Could you try to install typings for clipboard ? for example in your typings.json add the following in globalDependencies. 

 `"clipboard": "github:DefinitelyTyped/DefinitelyTyped/clipboard/clipboard.d.ts#56295f5058cac7ae458540423c50ac2dcf9fc711" `

and run `typings install`

**Comment by maxisam** [comment]
does it work ?

**Comment by xcuben** [comment]
Unfortunately no...
I still think that installing clipboard module in npm would be the reason but even that didnt resolve the problem . 
Plz tell me if u have any other suggestions.

Thanks

**Comment by maxisam** [comment]
You tried the typings solution I mentioned ?

**Comment by xcuben** [comment]
here it is : 
{
  "ambientDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654",
    "jasmine": "registry:dt/jasmine#2.2.0+20160412134438",
    "node": "registry:dt/node#4.0.0+20160509154515",
"clipboard":"github:DefinitelyTyped/DefinitelyTyped/clipboard/clipboard.d.ts#56295f5058cac7ae458540423c50ac2dcf9fc711"
  },
  "dependencies": {
    "moment": "registry:npm/moment#2.10.5+20160211003958"
  }
}

**Comment by maxisam** [comment]
it seems correct. I used this module in my project as well, so I think it should work. And it works in the example, so there must be something wrong in typescript related setting. If you really wanna fix it, put a sample project on github that can repeat this issue.

**Comment by xcuben** [comment]
Thanks 
I'll try to do it if i can not fix alone

**Comment by xcuben** [comment]
Hi @maxisam 
So I Tried to upgrade my @angular/core and @angular/common from rc.1 to rc.4 and the clipboard functionality does the work but I still have the errors . 
I know it s wierd but I dont found any explanation for it 
PS: I also saw that there was another closed Issue for the same Problem . Could you plz try to See if is there any compatiblities Problems?

Thanks

**Comment by maxisam** [comment]
I actually tried. It is working on my end. Maybe  you can create an example on github so I can try to help you. Btw, I just noticed your typings and typescript are outdated. You might want to update them.

**Comment by xcuben** [comment]
THanks a lot
