### ISSUE TITLE
RC5 gives errors

### ISSUE THREAD

**Issue by vapits** [maxisam/angular2-clipboard#6]
Awesome module, though in RC5 is not working.
Giving a following errors:

> metadata_resolver.js:704Uncaught TypeError: Cannot read property 'type' of null(anonymous function) @ metadata_resolver.js:704getTransitiveModules @ metadata_resolver.js:703CompileMetadataResolver._getTransitiveNgModuleMetadata @ metadata_resolver.js:417CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:289RuntimeCompiler._compileComponents @ runtime_compiler.js:157RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:79RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:56PlatformRef_._bootstrapModuleWithZone @ application_ref.js:374PlatformRef_.bootstrapModule @ application_ref.js:367(anonymous function) @ main.ts:9__webpack_require__ @ bootstrap f173efc…:52(anonymous function) @ ngii-clipboard.directive.ts:20__webpack_require__ @ bootstrap f173efc…:52webpackJsonpCallback @ bootstrap f173efc…:23(anonymous function) @ main.bundle.js:1
client:54 [WDS] Errors while compiling.
client:56 [default] /Projects/WebApp/node_modules/angular2-clipboard/src/ngii-clipboard.directive.ts:2:0 
Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.errors @ client:56sock.onmessage @ client:90EventTarget.dispatchEvent @ eventtarget.js:58(anonymous function) @ main.js:299SockJS._transportMessage @ main.js:297EventEmitter.emit @ emitter.js:50WebSocketTransport.ws.onmessage @ websocket.js:60wrapFn @ zone.js:769ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
client:56 [default] /Projects/WebApp/node_modules/angular2-clipboard/src/ngii-clipboard.directive.ts:2:27 
Cannot find module 'clipboard'.errors @ client:56sock.onmessage @ client:90EventTarget.dispatchEvent @ eventtarget.js:58(anonymous function) @ main.js:299SockJS._transportMessage @ main.js:297EventEmitter.emit @ emitter.js:50WebSocketTransport.ws.onmessage @ websocket.js:60wrapFn @ zone.js:769ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
client:56 [default] /Projects/WebApp/node_modules/angular2-clipboard/src/ngii-clipboard.directive.ts:21:20 
Cannot find name 'ClipboardOptions'.

**Comment by maxisam** [comment]
I haven't upgrade it to RC5. I will probably do it this week. Thx

**Comment by maxisam** [comment]
It is updated to RC6. Thx
